markdown: redcarpet
title: Spinoza
baseurl: /spinoza
pygments: true
exclude: ['README.md']
# Build settings
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
